"""add table excurtion_photo and connect with excurtion

Revision ID: 520242177751
Revises: d45ac214acf3
Create Date: 2025-04-25 20:34:08.363662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "520242177751"
down_revision: Union[str, None] = "d45ac214acf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excursionphotos",
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("photo_number", sa.Integer(), nullable=False),
        sa.Column("excursion_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["excursion_id"],
            ["post_excurtions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("excursionphotos")
    # ### end Alembic commands ###
