"""change name column to description

Revision ID: 550807c8e968
Revises: 922c3b53110e
Create Date: 2025-04-22 17:27:53.406089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "550807c8e968"
down_revision: Union[str, None] = "922c3b53110e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_excurtions",
        sa.Column("description", sa.Text(), server_default="", nullable=False),
    )
    op.drop_column("post_excurtions", "body")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_excurtions",
        sa.Column("body", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    )
    op.drop_column("post_excurtions", "description")
    # ### end Alembic commands ###
