"""change name

Revision ID: 5d6c20c635ae
Revises: 520242177751
Create Date: 2025-04-25 20:36:35.919663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d6c20c635ae"
down_revision: Union[str, None] = "520242177751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excursion_photos",
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("photo_number", sa.Integer(), nullable=False),
        sa.Column("excursion_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["excursion_id"],
            ["post_excurtions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("excursionphotos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excursionphotos",
        sa.Column("file_path", sa.VARCHAR(length=255), nullable=False),
        sa.Column("photo_number", sa.INTEGER(), nullable=False),
        sa.Column("excursion_id", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["excursion_id"],
            ["post_excurtions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("excursion_photos")
    # ### end Alembic commands ###
