"""add column city, has_children, date, persons_count, date, status in post table

Revision ID: 8df604ff39a8
Revises: 550807c8e968
Create Date: 2025-04-22 18:21:43.412323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8df604ff39a8"
down_revision: Union[str, None] = "550807c8e968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_excurtions", sa.Column("city", sa.String(length=30), nullable=False)
    )
    op.add_column(
        "post_excurtions",
        sa.Column("has_childen", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "post_excurtions",
        sa.Column("persons_count", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column("post_excurtions", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column(
        "post_excurtions",
        sa.Column(
            "status", sa.String(length=20), server_default="change", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post_excurtions", "status")
    op.drop_column("post_excurtions", "date")
    op.drop_column("post_excurtions", "persons_count")
    op.drop_column("post_excurtions", "has_childen")
    op.drop_column("post_excurtions", "city")
    # ### end Alembic commands ###
