"""add column avatar to guide

Revision ID: d45ac214acf3
Revises: 8df604ff39a8
Create Date: 2025-04-22 19:33:01.608210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d45ac214acf3"
down_revision: Union[str, None] = "8df604ff39a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_guides",
        sa.Column(
            "avatar",
            sa.String(length=255),
            nullable=True,
            photo_path="Путь к файлу фотографии",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_guides", "avatar")
    # ### end Alembic commands ###
